
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pau_d
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }
    
    public static double redondeoDecimales(double numero, int numeroDecimales) {
    BigDecimal redondeado = new BigDecimal(numero)
                                .setScale(numeroDecimales, RoundingMode.HALF_EVEN);
    return redondeado.doubleValue();
}
    
    double elNumero =  0.0;
   public Escritorio(double num)
    {
        elNumero = num;
    }
 
    //Convierte un numero en notacion cientifica a numero normal
    //el numero se supone ya fue especificado en el constructor
    public String conversion()
    {
      return conversion(elNumero);
    }
 
    //Convierte un numero en notacion cientifica a numero normal
    public String conversion(double valor)
    {
      Locale.setDefault(Locale.US);
      DecimalFormat num = new DecimalFormat("####.####");
      return num.format(valor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablanumeros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaxi = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaxu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaxr = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablafxi = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablafxr = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablair = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtxi = new javax.swing.JTextField();
        txtxu = new javax.swing.JTextField();
        txtecuacion = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metodo Biseccion");

        tablanumeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablanumeros);

        tablaxi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(tablaxi);

        tablaxu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(tablaxu);

        tablaxr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(tablaxr);

        tablafxi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane5.setViewportView(tablafxi);

        tablafxr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane6.setViewportView(tablafxr);

        tablair.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane7.setViewportView(tablair);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Xi=");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Xu=");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ecuacion=");

        btnenviar.setBackground(new java.awt.Color(0, 0, 0));
        btnenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtxi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtecuacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtxu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(btnenviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtecuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed

         Escritorio con = new Escritorio();
        
        ArrayList<Integer> listaite = new ArrayList<Integer>();
        ArrayList<Double> listaxi = new ArrayList<Double>();
        ArrayList<Double> listaxu = new ArrayList<Double>();
        ArrayList<Double> listaxr = new ArrayList<Double>();
        ArrayList<Double> listafxi = new ArrayList<Double>();
        ArrayList<Double> listafxr = new ArrayList<Double>();
        ArrayList<Double> listafir = new ArrayList<Double>();

        double xi;
        double xu;
        double xr;
        double fxi = 0;
        double fxr;
        double fir;
        String ecuacion;
        int iteracciones;

        xi = Double.valueOf(txtxi.getText());
        xu = Double.valueOf(txtxu.getText());
        ecuacion = txtecuacion.getText();
//        iteracciones = Integer.parseInt(txtiteracciones.getText());
        int ite=1;
        Funcion f = new Funcion(ecuacion);

        //tabla iteracciones
//        for (int i = 0; i < ; i++) {
//            listaite.add(i + 1);
//        }

        
        do{
            
            
            
            listaite.add(ite);
            listaxi.add(redondeoDecimales(xi, 4));
            listaxu.add(redondeoDecimales(xu, 4));

            xr = redondeoDecimales((xi + xu) / 2, 4);            
            listaxr.add(xr);

            fxi = redondeoDecimales(f.eval(xi), 4);
            listafxi.add(fxi);

            fxr = Double.parseDouble(con.conversion(f.eval(xr)));
            listafxr.add(fxr);

            fir = Double.parseDouble(con.conversion(fxi * fxr));
            listafir.add(fir);
            
            if (fir > 0) {
                xi = redondeoDecimales(xr, 4);
            } else {
                xu = redondeoDecimales(xr, 4);
            }
            ite++;
            
            if(fir==0){
                break;
            }
        }while(true);
       
        //iteracciones
        String matriz[][] = new String[listaite.size()][1];

        for (int i = 0; i < listaite.size(); i++) {
            matriz[i][0] = listaite.get(i).toString();
        }

        tablanumeros.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Iteracciones"
                }
        ));

        
        
        //tabla xi
        String matriz2[][] = new String[listaxi.size()][1];

        for (int i = 0; i < listaxi.size(); i++) {
            matriz2[i][0] = listaxi.get(i).toString();
        }
        
        tablaxi.setModel(new javax.swing.table.DefaultTableModel(
                matriz2,
                new String[]{
                    "Xi"
                }
        ));

        //tabla xu
        String matriz3[][] = new String[listaxu.size()][1];

        for (int i = 0; i < listaxu.size(); i++) {
            matriz3[i][0] = listaxu.get(i).toString();
        }
        
        tablaxu.setModel(new javax.swing.table.DefaultTableModel(
                matriz3,
                new String[]{
                    "Xu"
                }
        ));
        
        //tabla xr
        String matriz4[][] = new String[listaxr.size()][1];

        for (int i = 0; i < listaxr.size(); i++) {
            matriz4[i][0] = listaxr.get(i).toString();
        }
        
        tablaxr.setModel(new javax.swing.table.DefaultTableModel(
                matriz4,
                new String[]{
                    "Xr"
                }
        ));
        
        //tabla f(xi)
        String matriz5[][] = new String[listafxi.size()][1];

        for (int i = 0; i < listafxi.size(); i++) {
            matriz5[i][0] = listafxi.get(i).toString();
        }
        
        tablafxi.setModel(new javax.swing.table.DefaultTableModel(
                matriz5,
                new String[]{
                    "F(xi)"
                }
        ));
        
        //tabla f(xr)
        String matriz6[][] = new String[listafxr.size()][1];

        for (int i = 0; i < listafxr.size(); i++) {
            matriz6[i][0] = listafxr.get(i).toString();
        }
        
        tablafxr.setModel(new javax.swing.table.DefaultTableModel(
                matriz6,
                new String[]{
                    "F(xr)"
                }
        ));
        
        //tabla f(xi)*f(xr)
        String matriz7[][] = new String[listafir.size()][1];

        for (int i = 0; i < listafir.size(); i++) {
            matriz7[i][0] = listafir.get(i).toString();
        }
        
        tablair.setModel(new javax.swing.table.DefaultTableModel(
                matriz7,
                new String[]{
                    "F(xi)*F(xr)"
                }
        ));
        


    }//GEN-LAST:event_btnenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tablafxi;
    private javax.swing.JTable tablafxr;
    private javax.swing.JTable tablair;
    private javax.swing.JTable tablanumeros;
    private javax.swing.JTable tablaxi;
    private javax.swing.JTable tablaxr;
    private javax.swing.JTable tablaxu;
    private javax.swing.JTextField txtecuacion;
    private javax.swing.JTextField txtxi;
    private javax.swing.JTextField txtxu;
    // End of variables declaration//GEN-END:variables
}
